// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/BrutalistOutdoorRebrandScreen-48O3jS/App.tsx": () => import("../components/mockups/templates/BrutalistOutdoorRebrandScreen-48O3jS/App.tsx"),
  "./components/mockups/templates/BrutalistOutdoorRebrandScreen-UUNkBG/App.tsx": () => import("../components/mockups/templates/BrutalistOutdoorRebrandScreen-UUNkBG/App.tsx"),
  "./components/mockups/templates/BrutalistOutdoorRebrandScreen-Isgu-t/App.tsx": () => import("../components/mockups/templates/BrutalistOutdoorRebrandScreen-Isgu-t/App.tsx"),
  "./components/mockups/templates/BrutalistOutdoorRebrandScreen-wMECA5/App.tsx": () => import("../components/mockups/templates/BrutalistOutdoorRebrandScreen-wMECA5/App.tsx"),
  "./components/mockups/templates/RetroFilmCrowdfundingApp-_TfzIb/App.tsx": () => import("../components/mockups/templates/RetroFilmCrowdfundingApp-_TfzIb/App.tsx")
};
